"use client"
// import type { Metadata } from 'next';
import './globals.css';
import './reset.css';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
